# Generated by Django 5.1.6 on 2025-03-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
