# Generated by Django 5.1.6 on 2025-03-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfuel', models.CharField(choices=[('CNG', 'CNG'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=50)),
                ('stransmission', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], max_length=50)),
                ('cname', models.CharField(max_length=100)),
                ('milegae', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('desc', models.TextField()),
                ('air', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=True)),
                ('childseat', models.BooleanField(default=True)),
                ('luggage', models.BooleanField(default=True)),
                ('music', models.BooleanField(default=False)),
                ('seatbelt', models.BooleanField(default=True)),
                ('sleepingbed', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=True)),
                ('onboardcomputer', models.BooleanField(default=False)),
                ('audioinput', models.BooleanField(default=True)),
                ('longtermtips', models.BooleanField(default=True)),
                ('carkit', models.BooleanField(default=True)),
                ('remotecontrollocking', models.BooleanField(default=True)),
                ('climatecontrol', models.BooleanField(default=True)),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
