# Generated by Django 5.1.6 on 2025-03-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_password1_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cimage',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='cprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
