# Generated by Django 5.1.5 on 2025-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_car_cimage_car_cprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='luggage',
            field=models.TextField(default=True),
        ),
    ]
